version: "3.9"

services:
  db:
    image: postgres:13
    container_name: unicatech-db
    environment:
      POSTGRES_USER: unicatech
      POSTGRES_PASSWORD: abelfera
      POSTGRES_DB: unicatech
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - unicatech-net

  app:
    build: .
    container_name: unicatech-app
    command: >
      sh -c "chmod +x /wait-for-it.sh &&
             /wait-for-it.sh db:5432 --
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db
    networks:
      - unicatech-net

volumes:
  postgres_data:

networks:
  unicatech-net:
    driver: bridge