# Generated by Django 4.1.5 on 2023-03-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('categoria', models.CharField(max_length=200, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nomeFornecedor', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('contaCredito', models.IntegerField()),
                ('contaDebito', models.IntegerField()),
                ('valorCredito', models.FloatField(default=0)),
                ('valorDebito', models.FloatField(default=0)),
                ('identificadorCompra', models.IntegerField()),
                ('identificadorvenda', models.IntegerField()),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('SKU', models.CharField(max_length=10, verbose_name='SKU')),
                ('NomeProduto', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproduto', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nomeConta', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('taxas', models.FloatField()),
                ('saldoInicial', models.FloatField(blank=True, default=None)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('taxacartao1', models.FloatField(default=0)),
                ('taxacartao2', models.FloatField(default=0)),
                ('taxacartao3', models.FloatField(default=0)),
                ('taxacartao4', models.FloatField(default=0)),
                ('taxacartao5', models.FloatField(default=0)),
                ('taxacartao6', models.FloatField(default=0)),
                ('taxacartao7', models.FloatField(default=0)),
                ('taxacartao8', models.FloatField(default=0)),
                ('taxacartao9', models.FloatField(default=0)),
                ('taxacartao10', models.FloatField(default=0)),
                ('taxacartao11', models.FloatField(default=0)),
                ('taxacartao12', models.FloatField(default=0)),
                ('taxacartao13', models.FloatField(default=0)),
                ('taxacartao14', models.FloatField(default=0)),
                ('taxacartao15', models.FloatField(default=0)),
                ('taxacartao16', models.FloatField(default=0)),
                ('taxacartao17', models.FloatField(default=0)),
                ('taxacartao18', models.FloatField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaconta', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quantidadeProduto', models.FloatField(default=0)),
                ('precoProduto', models.FloatField(default=0)),
                ('frete', models.FloatField(default=0)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('identificadorCompra', models.IntegerField()),
                ('dataCompra', models.DateField(verbose_name='Data da Compra')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor', verbose_name='Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto', verbose_name='Produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
