# Generated by Django 4.1.5 on 2023-03-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_movimentacaoconta_identificadorcompra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacaoconta',
            old_name='identificadorvenda',
            new_name='identificadorVenda',
        ),
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='contaCredito',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='contaDebito',
            field=models.IntegerField(default=0),
        ),
    ]
