# Generated by Django 4.1.5 on 2023-03-10 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_localizacaocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='idLocalizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.localizacaocompra', verbose_name='Localização'),
            preserve_default=False,
        ),
    ]
