# Generated by Django 4.1.5 on 2023-04-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_compra_idlocalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='conta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.conta', verbose_name='Produto'),
            preserve_default=False,
        ),
    ]
