# Generated by Django 4.1.5 on 2023-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_compra_conta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaconta",
            name="criados",
            field=models.DateField(verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="categoriaconta",
            name="modificado",
            field=models.DateField(auto_now_add=True, verbose_name="Atualização"),
        ),
        migrations.AlterField(
            model_name="categoriaproduto",
            name="criados",
            field=models.DateField(verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="categoriaproduto",
            name="modificado",
            field=models.DateField(auto_now_add=True, verbose_name="Atualização"),
        ),
        migrations.AlterField(
            model_name="compra",
            name="criados",
            field=models.DateField(verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="compra",
            name="modificado",
            field=models.DateField(auto_now_add=True, verbose_name="Atualização"),
        ),
        migrations.AlterField(
            model_name="conta",
            name="criados",
            field=models.DateField(verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="conta",
            name="modificado",
            field=models.DateField(auto_now_add=True, verbose_name="Atualização"),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="criados",
            field=models.DateField(verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="modificado",
            field=models.DateField(auto_now_add=True, verbose_name="Atualização"),
        ),
        migrations.AlterField(
            model_name="localizacaocompra",
            name="criados",
            field=models.DateField(verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="localizacaocompra",
            name="modificado",
            field=models.DateField(auto_now_add=True, verbose_name="Atualização"),
        ),
        migrations.AlterField(
            model_name="movimentacaoconta",
            name="criados",
            field=models.DateField(verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="movimentacaoconta",
            name="modificado",
            field=models.DateField(auto_now_add=True, verbose_name="Atualização"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="criados",
            field=models.DateField(verbose_name="Criação"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="modificado",
            field=models.DateField(auto_now_add=True, verbose_name="Atualização"),
        ),
    ]
