# Generated by Django 4.1.5 on 2023-04-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_venda_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.AddField(
            model_name='venda',
            name='conta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.conta', verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
