# Generated by Django 4.1.5 on 2023-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_movimentacaoconta_contacredito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(verbose_name='Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('bandeira_cartao', models.CharField(max_length=20, verbose_name='Bandeira do Cartão')),
                ('taxa_cartao1', models.FloatField(default=0)),
                ('taxa_cartao2', models.FloatField(default=0)),
                ('taxa_cartao3', models.FloatField(default=0)),
                ('taxa_cartao4', models.FloatField(default=0)),
                ('taxa_cartao5', models.FloatField(default=0)),
                ('taxa_cartao6', models.FloatField(default=0)),
                ('taxa_cartao7', models.FloatField(default=0)),
                ('taxa_cartao8', models.FloatField(default=0)),
                ('taxa_cartao9', models.FloatField(default=0)),
                ('taxa_cartao10', models.FloatField(default=0)),
                ('taxa_cartao11', models.FloatField(default=0)),
                ('taxa_cartao12', models.FloatField(default=0)),
                ('taxa_cartao13', models.FloatField(default=0)),
                ('taxa_cartao14', models.FloatField(default=0)),
                ('taxa_cartao15', models.FloatField(default=0)),
                ('taxa_cartao16', models.FloatField(default=0)),
                ('taxa_cartao17', models.FloatField(default=0)),
                ('taxa_cartao18', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
