# Generated by Django 4.1.5 on 2023-05-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cartao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao1',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao10',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao11',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao12',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao13',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao14',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao15',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao16',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao17',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao18',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao2',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao3',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao4',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao5',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao6',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao7',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao8',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='taxacartao9',
        ),
    ]
