# Generated by Django 4.1.5 on 2023-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_conta_taxacartao1_remove_conta_taxacartao10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='taxacartao1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao10',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao11',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao13',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao14',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao15',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao16',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao17',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao18',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao8',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conta',
            name='taxacartao9',
            field=models.FloatField(default=0),
        ),
    ]
