# Generated by Django 4.1.5 on 2023-05-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_conta_taxacartao1_conta_taxacartao10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartao',
        ),
    ]
