# Generated by Django 4.1.5 on 2023-05-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_delete_cartao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(verbose_name='Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('taxacartao1', models.FloatField(default=0)),
                ('taxacartao2', models.FloatField(default=0)),
                ('taxacartao3', models.FloatField(default=0)),
                ('taxacartao4', models.FloatField(default=0)),
                ('taxacartao5', models.FloatField(default=0)),
                ('taxacartao6', models.FloatField(default=0)),
                ('taxacartao7', models.FloatField(default=0)),
                ('taxacartao8', models.FloatField(default=0)),
                ('taxacartao9', models.FloatField(default=0)),
                ('taxacartao10', models.FloatField(default=0)),
                ('taxacartao11', models.FloatField(default=0)),
                ('taxacartao12', models.FloatField(default=0)),
                ('taxacartao13', models.FloatField(default=0)),
                ('taxacartao14', models.FloatField(default=0)),
                ('taxacartao15', models.FloatField(default=0)),
                ('taxacartao16', models.FloatField(default=0)),
                ('taxacartao17', models.FloatField(default=0)),
                ('taxacartao18', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
