# Generated by Django 4.1.5 on 2023-05-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cartao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao1',
            new_name='taxa_cartao1',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao10',
            new_name='taxa_cartao10',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao11',
            new_name='taxa_cartao11',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao12',
            new_name='taxa_cartao12',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao13',
            new_name='taxa_cartao13',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao14',
            new_name='taxa_cartao14',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao15',
            new_name='taxa_cartao15',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao16',
            new_name='taxa_cartao16',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao17',
            new_name='taxa_cartao17',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao18',
            new_name='taxa_cartao18',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao2',
            new_name='taxa_cartao2',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao3',
            new_name='taxa_cartao3',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao4',
            new_name='taxa_cartao4',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao5',
            new_name='taxa_cartao5',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao6',
            new_name='taxa_cartao6',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao7',
            new_name='taxa_cartao7',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao8',
            new_name='taxa_cartao8',
        ),
        migrations.RenameField(
            model_name='cartao',
            old_name='taxacartao9',
            new_name='taxa_cartao9',
        ),
    ]
