# Generated by Django 4.1.5 on 2023-05-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cartao_bandeira_cartao_cartao_cartao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='cartao',
        ),
    ]
