# Generated by Django 4.1.5 on 2023-05-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_cartao_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cartao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cartao', verbose_name='Tipo'),
        ),
    ]
