# Generated by Django 4.1.5 on 2023-05-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_conta_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='cartao',
            field=models.IntegerField(null=True),
        ),
    ]
