# Generated by Django 4.1.5 on 2023-05-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_cartao_cartao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
