# Generated by Django 4.1.5 on 2023-05-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_delete_compra_delete_localizacaocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoconta',
            name='contaCredito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.conta', verbose_name='Conta'),
        ),
    ]
