# Generated by Django 4.1.5 on 2023-05-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_alter_compra_produto'),
        ('core', '0034_alter_movimentacaoconta_contacredito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaProduto',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
