# Generated by Django 4.1.5 on 2023-05-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0006_alter_compra_conta'),
        ('core', '0036_delete_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='cartao',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='movimentacaoconta',
            name='contaCredito',
        ),
        migrations.DeleteModel(
            name='Cartao',
        ),
        migrations.DeleteModel(
            name='CategoriaConta',
        ),
        migrations.DeleteModel(
            name='Conta',
        ),
        migrations.DeleteModel(
            name='MovimentacaoConta',
        ),
    ]
