# Generated by Django 4.1.5 on 2023-05-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0003_cliente_remove_venda_cliente'),
        ('core', '0037_remove_conta_cartao_remove_conta_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
