# Generated by Django 4.1.5 on 2025-08-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
