# Generated by Django 4.2.23 on 2026-01-18 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0040_delete_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=200, verbose_name='Localização')),
                ('novo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('icone', models.CharField(max_length=200, verbose_name='Icone')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_criados', to=settings.AUTH_USER_MODEL)),
                ('usuarios_vistos', models.ManyToManyField(blank=True, related_name='alertas_vistos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
