# Generated by Django 4.2.23 on 2026-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='identificador_compra',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertas',
            name='identificador_servico',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertas',
            name='identificador_venda',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
