# Generated by Django 4.2.23 on 2026-08-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alertas_identificador_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='identificador_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertas',
            name='identificador_servico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertas',
            name='identificador_venda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
