# Generated by Django 4.1.5 on 2023-05-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contas.categoriaconta', verbose_name='Tipo'),
        ),
    ]
