# Generated by Django 4.1.5 on 2023-05-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0004_alter_movimentacaoconta_contacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoconta',
            name='cotacaoDolar',
            field=models.FloatField(default=0),
        ),
    ]
