# Generated by Django 4.1.5 on 2023-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0005_movimentacaoconta_cotacaodolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoconta',
            name='identificadorDolar',
            field=models.BooleanField(default=True, verbose_name='Dólar?'),
        ),
    ]
