# Generated by Django 4.1.5 on 2023-06-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0006_movimentacaoconta_identificadordolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='cartao',
            field=models.IntegerField(null=True),
        ),
    ]
