# Generated by Django 4.1.5 on 2023-10-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0007_alter_conta_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='valorDolarMedio',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
