# Generated by Django 4.1.5 on 2023-10-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0008_conta_valordolarmedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='valorDolarMedio',
            field=models.FloatField(default=0),
        ),
    ]
