# Generated by Django 4.1.5 on 2023-10-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0009_alter_conta_valordolarmedio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='valorDolarMedio',
            new_name='valor_dolar_medio',
        ),
    ]
