# Generated by Django 4.1.5 on 2023-10-31 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0010_rename_valordolarmedio_conta_valor_dolar_medio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='saldoInicial',
        ),
    ]
