# Generated by Django 4.1.5 on 2023-11-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0011_remove_conta_saldoinicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='bandeira_cartao',
        ),
        migrations.AddField(
            model_name='cartao',
            name='taxa_debito',
            field=models.FloatField(default=0),
        ),
    ]
