# Generated by Django 4.1.5 on 2023-11-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0012_remove_cartao_bandeira_cartao_cartao_taxa_debito'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(verbose_name='Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valor', models.FloatField(default=0)),
                ('parcelas', models.IntegerField()),
                ('bandeira', models.CharField(max_length=200, verbose_name='Descrição')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contas.cartao', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
