# Generated by Django 4.1.5 on 2023-11-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0013_recebimentocartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentocartao',
            name='identificador_venda',
            field=models.IntegerField(default=0),
        ),
    ]
