# Generated by Django 4.1.5 on 2023-11-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0014_recebimentocartao_identificador_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recebimentocartao',
            name='cartao',
        ),
        migrations.AddField(
            model_name='recebimentocartao',
            name='conta_cartao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contas.conta', verbose_name='Conta'),
        ),
    ]
