# Generated by Django 4.1.5 on 2024-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0015_remove_recebimentocartao_cartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='taxa_wire',
            field=models.FloatField(default=0),
        ),
    ]
