# Generated by Django 4.1.5 on 2024-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0016_conta_taxa_wire'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentocartao',
            name='valor_liquido',
            field=models.FloatField(default=0),
        ),
    ]
