# Generated by Django 4.2.23 on 2026-06-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0017_recebimentocartao_valor_liquido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recebimentocartao',
            name='bandeira',
        ),
    ]
