# Generated by Django 4.1.5 on 2023-05-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0003_cliente_remove_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Vendas.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
