# Generated by Django 4.1.5 on 2023-07-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0004_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='lucro',
            field=models.FloatField(default=0),
        ),
    ]
