# Generated by Django 4.2.23 on 2026-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0006_venda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='identificador_servico',
            field=models.IntegerField(default=0),
        ),
    ]
