# Generated by Django 4.2.23 on 2026-07-22 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vendas', '0006_venda_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(verbose_name='Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('identificador_servico', models.IntegerField()),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('preco_servico', models.FloatField(default=0)),
                ('imei', models.CharField(max_length=200, verbose_name='Descrição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendas.cliente', verbose_name='Cliente')),
                ('id_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendas.venda', verbose_name='Venda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
