# Generated by Django 4.2.23 on 2026-07-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_venda',
            field=models.IntegerField(),
        ),
    ]
