# Generated by Django 4.2.23 on 2026-07-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0002_alter_servico_id_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id_venda',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
