# Generated by Django 4.2.23 on 2026-07-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0003_alter_servico_id_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='imei',
        ),
    ]
