# Generated by Django 4.2.23 on 2026-07-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0004_remove_servico_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='imei',
            field=models.CharField(default=0, max_length=200, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
