# Generated by Django 4.2.23 on 2026-07-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicos', '0007_remove_servico_solucao_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
