# Generated by Django 4.1.5 on 2023-05-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_alter_compra_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fornecedor',
        ),
    ]
