# Generated by Django 4.1.5 on 2023-05-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_produto_categoria_delete_categoriaproduto_and_more'),
        ('Compras', '0003_remove_compra_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor', verbose_name='Fornecedor'),
            preserve_default=False,
        ),
    ]
