# Generated by Django 4.1.5 on 2023-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0003_fornecedor_alter_compra_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='remover',
            field=models.FloatField(default=0),
        ),
    ]
