# Generated by Django 4.1.5 on 2023-05-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0004_compra_remover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='remover',
        ),
    ]
