# Generated by Django 4.1.5 on 2023-05-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0004_alter_movimentacaoconta_contacredito'),
        ('Compras', '0006_alter_compra_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contas.conta', verbose_name='Produto'),
        ),
    ]
