# Generated by Django 4.1.5 on 2023-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0007_alter_compra_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='valorDolarMedio',
            field=models.FloatField(default=0),
        ),
    ]
