# Generated by Django 4.1.5 on 2023-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0008_compra_valordolarmedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='quantidadeProduto',
            field=models.IntegerField(default=0),
        ),
    ]
