# Generated by Django 4.1.5 on 2023-10-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0009_alter_compra_quantidadeproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='localizacaoCompra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Compras.localizacaocompra', verbose_name='Localização da Compra'),
            preserve_default=False,
        ),
    ]
