# Generated by Django 4.1.5 on 2023-12-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0010_fornecedor_localizacaocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deslocamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(verbose_name='Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('origem', models.IntegerField()),
                ('destino', models.IntegerField()),
                ('frete', models.FloatField(default=0)),
                ('identificadorCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compras.compra', verbose_name='Localização')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
