# Generated by Django 4.1.5 on 2023-12-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0011_deslocamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deslocamento',
            name='identificadorCompra',
            field=models.IntegerField(),
        ),
    ]
