# Generated by Django 4.1.5 on 2024-01-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0012_alter_deslocamento_identificadorcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='deslocamento',
            name='idMovimentacaoConta',
            field=models.IntegerField(default=343),
            preserve_default=False,
        ),
    ]
