# Generated by Django 4.1.5 on 2024-01-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0013_deslocamento_idmovimentacaoconta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacaocompra',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
