# Generated by Django 4.1.5 on 2024-01-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0014_alter_localizacaocompra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deslocamento',
            name='destino',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deslocamento',
            name='origem',
            field=models.IntegerField(null=True),
        ),
    ]
