# Generated by Django 4.1.5 on 2024-01-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0015_alter_deslocamento_destino_alter_deslocamento_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deslocamento',
            name='idMovimentacaoConta',
            field=models.IntegerField(null=True),
        ),
    ]
