# Generated by Django 4.1.5 on 2023-09-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Despesas.categoriadespesa', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
