# Generated by Django 4.1.5 on 2023-09-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Despesas', '0004_despesa_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='categoria',
        ),
    ]
