# Generated by Django 4.1.5 on 2023-10-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Despesas', '0005_remove_despesa_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaDespesa',
        ),
    ]
