# Generated by Django 4.1.5 on 2023-10-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Despesas', '0006_delete_categoriadespesa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesa',
            new_name='CadastroDespesa',
        ),
    ]
