# Generated by Django 4.1.5 on 2023-10-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0007_alter_conta_cartao'),
        ('Despesas', '0007_rename_despesa_cadastrodespesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrodespesa',
            name='conta_debito',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Contas.conta', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
