# Generated by Django 4.1.5 on 2024-01-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0016_conta_taxa_wire'),
        ('Despesas', '0008_cadastrodespesa_conta_debito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(verbose_name='Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Despesas.cadastrodespesa', verbose_name='Tipo')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contas.movimentacaoconta', verbose_name='Tipo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
