# Generated by Django 4.1.5 on 2024-01-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0016_conta_taxa_wire'),
        ('Despesas', '0009_despesas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesas',
            new_name='Despesa',
        ),
    ]
